Reduce integer size for line number when parsing .wast files The testsuite was failing with:
```
zig-aarch64-macos-0.15.1/lib/std/json/static.zig:572:44: error: type 'f64' cannot represent integer value '18446744073709551615'
                    if (f > std.math.maxInt(T)) return error.Overflow;
```

Interestingly in an example .wast (e.g. test-token's token.wast) the
line numbers are 4 and 8:

```
{"source_filename": "/Users/malcolm/.cache/zig/p/N-V-__8AAKtbtgBFkB_BMIKSUqC-temKvHmuqBSvjBlf4hD6/token.wast",
 "commands": [
  {"type": "assert_malformed", "line": 4, "filename": "token.0.wat", "text": "unknown operator", "module_type": "text"},
  {"type": "assert_malformed", "line": 8, "filename": "token.1.wat", "text": "unknown operator", "module_type": "text"}]}
```

which is hinting at maybe the json parser code running on
uninitialised data? Not sure.

Anyway, usize is way larger than we need anyway so dropping down to
u32 (say) is totally fine.